name: Auto Assign
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
jobs:
  auto-assign:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: 'Identify event type'
        id: identify-event
        run: |
          echo "Event type: ${{ github.event.name }}"
          # Set output for conditional steps
          if [[ ${{ github.event.name }} == 'issues' ]]; then
            echo "::set-output name=event_type::issue"
          else
            echo "::set-output name=event_type::pull_request"
          fi
      - name: 'Auto-assign (issue)'
        if: steps.identify-event.outputs.event_type == 'issue'
        uses: pozil/auto-assign-issue@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: jib-data
          numOfAssignee: 1
      - name: 'Auto-assign (pull request)'
        if: steps.identify-event.outputs.event_type == 'pull_request'
        uses: pozil/auto-assign-issue@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: jizzel
          numOfAssignee: 1
